### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'name_scope'

### ISSUE THREAD

**Issue by anthonyyuan** [PaddlePaddle/PaddleFormers#634] opened 2020-05-27 04:26 UTC
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.7.0，PaddlePaddle
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
Traceback (most recent call last):
  File "/home/anthony/.local/bin/hub", line 10, in <module>
    sys.exit(main())
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/commands/run.py", line 232, in execute
    self.module = self.find_module(module_name)
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/commands/run.py", line 71, in find_module
    return hub.Module(directory=module_dir[0])
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/module/module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/home/anthony/.local/lib/python3.7/site-packages/paddlehub/module/module.py", line 138, in __init__
    super(Module, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'name_scope'

**Comment by nepeplwu** [comment] 2020-05-27 08:39
@anthonyyuan 感谢反馈，试试升级paddlepaddle到最新版本看看

**Comment by haoyuying** [comment] 2021-04-14 12:49
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:49 UTC
