### ISSUE TITLE
Senta 情感分析 Fine-tune

### ISSUE THREAD

**Issue by lynette2020** [PaddlePaddle/PaddleFormers#639] opened 2020-05-28 04:21 UTC
paddlehub==1.6.2
paddlepaddle==1.8.0

我按照
https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/demo/senta
步骤做，但是到
config = hub.RunConfig(
    use_cuda=False,
    use_pyreader=False,
    use_data_parallel=False,
    num_epoch=3,
    batch_size=32,
    strategy=hub.AdamWeightDecayStrategy())

后报错

Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 179, in __init__
    metrics_choices=metrics_choices)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 49, in __init__
    metrics_choices=metrics_choices)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 299, in __init__
    main_program, for_test=False)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\common\paddle_helper.py", line 274, in clone_program
    dest_program.global_block())
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\common\paddle_helper.py", line 147, in _copy_vars_and_ops_in_blocks
    var_info = copy.deepcopy(get_variable_info(var))
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\common\paddle_helper.py", line 65, in get_variable_info
    var_info['gradient_clip_attr'] = var.gradient_clip_attr
AttributeError: 'Parameter' object has no attribute 'gradient_clip_attr'

**Comment by lynette2020** [comment] 2020-05-28 04:29
原码

import paddlehub as hub

module = hub.Module(name="senta_bilstm")
inputs, outputs, program = module.context(trainable=True)

dataset = hub.dataset.ChnSentiCorp()
reader = hub.reader.LACClassifyReader(
    dataset=dataset,
    vocab_path=module.get_vocab_path())

strategy = hub.AdamWeightDecayStrategy(
    learning_rate=1e-5,
    weight_decay=0.01,
    warmup_proportion=0.1,
    lr_scheduler="linear_decay",
)

config = hub.RunConfig(use_cuda=False, num_epoch=3, batch_size=32, strategy=strategy)

sent_feature = outputs["sentence_feature"]

feed_list = [inputs["words"].name]

cls_task = hub.TextClassifierTask(
    data_reader=reader,
    feature=sent_feature,
    feed_list=feed_list,
    num_classes=dataset.num_labels,
    config=config)

**Comment by Steffy-zxf** [comment] 2020-05-28 07:51
你好！请升级paddlehub至最新版本1.7.1

```shell
$ pip install -U paddlehub
```

**Comment by lynette2020** [comment] 2020-05-28 08:53
多谢回复，升级之后运行最后一行代码报错

>>> cls_task.finetune_and_eval()
[2020-05-28 16:51:24,649] [    INFO] - processing train data now... this may take a few minutes
D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
[2020-05-28 16:52:04,163] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization,
D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-05-28 16:52:04,182] [    INFO] - Try loading checkpoint from ckpt_20200528164942\ckpt.meta
[2020-05-28 16:52:04,183] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-05-28 16:52:04,940] [    INFO] - PaddleHub finetune start
D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 868, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 889, in finetune
    run_states = self._run(do_eval=do_eval)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1082, in _run
    return_numpy=self.return_numpy)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\common\paddle_helper.py", line 168, in _copy_vars_and_ops_in_blocks
    to_block.append_op(**op_info)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\common\paddle_helper.py", line 276, in clone_program
    dest_program.global_block())
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 396, in _build_env
    self._base_main_program, for_test=False)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 508, in main_program
    self._build_env()
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 834, in load_checkpoint
    main_program=self.main_program)
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 367, in init_if_necessary
    if not self.load_checkpoint():
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 883, in finetune
    self.init_if_necessary()
  File "D:\Anaconda3\envs\sentiment\lib\site-packages\paddlehub\finetune\task\base_task.py", line 868, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.8.0cpu\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < lookup_table > error]

**Comment by lynette2020** [comment] 2020-05-28 08:55
paddlehub==1.7.1
paddlepaddle==1.8.0

原码

import paddlehub as hub

module = hub.Module(name="senta_bilstm")
inputs, outputs, program = module.context(trainable=True)
dataset = hub.dataset.ChnSentiCorp()
reader = hub.reader.LACClassifyReader(
    dataset=dataset,
    vocab_path=module.get_vocab_path())

strategy = hub.AdamWeightDecayStrategy(
    learning_rate=1e-5,
    weight_decay=0.01,
    warmup_proportion=0.1,
    lr_scheduler="linear_decay",
)

config = hub.RunConfig(use_cuda=False, num_epoch=3, batch_size=32, strategy=strategy)

sent_feature = outputs["sentence_feature"]

feed_list = [inputs["words"].name]

cls_task = hub.TextClassifierTask(
    data_reader=reader,
    feature=sent_feature,
    feed_list=feed_list,
    num_classes=dataset.num_labels,
    config=config)

cls_task.finetune_and_eval()

**Comment by Steffy-zxf** [comment] 2020-05-30 13:46
@lynette2020 你好！我在windows下paddle1.8.0 paddlehub1.7.1环境下没能复现你的错误。我这边运行正常。看看numpy的版本。我这边numpy版本为1.18.4，可以安装这个版本试试。

```shell
pip install numpy==1.18.4
```

**Comment by lynette2020** [comment] 2020-06-01 01:44
我的numpy版本是 numpy==1.18.4 还是相同的错误
我尝试了python版本3.6.10 和 3.7.7下的
paddlehub==1.7.1
paddlepaddle==1.8.0
都不行，我看了之前的几个issues好像是相同的问题：
https://github.com/PaddlePaddle/PaddleHub/issues/500
https://github.com/PaddlePaddle/PaddleHub/issues/473
https://github.com/PaddlePaddle/Paddle/issues/23504

降版本到1.6.2

module = hub.Module(name="senta_bilstm")
这句报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\module\module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\module\module.py", line 178, in init_with_name
    return cls.init_with_directory(directory=module_dir[0], **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\module\module.py", line 200, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\module\module.py", line 138, in __init__
    super(Module, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'name_scope'

**Comment by Steffy-zxf** [comment] 2020-06-01 01:52
你好！上述你提到的两个错误是不一样的。

> InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
[Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.8.0cpu\paddle\paddle/fluid/framework/tensor_impl.h:33)
[operator < lookup_table > error]

更换numpy版本之后，这个错误还会出现吗？

> TypeError: init() missing 1 required positional argument: 'name_scope'

这个错误，请升级paddlepaddle至1.8.0版本以上即可解决。

**Comment by lynette2020** [comment] 2020-06-01 01:56
您好，感谢回复，我的numpy版本本来就是1.18.4，会报错
避免被其他库影响，我新建了环境（python=3.6.10 和 3.7.7分别尝试），安装了
paddlehub==1.7.1
paddlepaddle==1.8.0
都是相同的错误

**Comment by lynette2020** [comment] 2020-06-01 04:20
[2020-06-01 09:22:07,050] [    INFO] - processing train data now... this may take a few minutes
D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
[2020-06-01 09:22:46,176] [    INFO] - Strategy with warmup, linear decay, slanted triangle learning rate, weight decay regularization,
D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-06-01 09:22:46,188] [    INFO] - Try loading checkpoint from ckpt_20200601092158\ckpt.meta
[2020-06-01 09:22:46,189] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-06-01 09:22:46,941] [    INFO] - PaddleHub finetune start
D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 868, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 889, in finetune
    run_states = self._run(do_eval=do_eval)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 1082, in _run
    return_numpy=self.return_numpy)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\envs\test\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\Anaconda3\envs\test\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\common\paddle_helper.py", line 168, in _copy_vars_and_ops_in_blocks
    to_block.append_op(**op_info)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\common\paddle_helper.py", line 276, in clone_program
    dest_program.global_block())
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 396, in _build_env
    self._base_main_program, for_test=False)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 508, in main_program
    self._build_env()
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 834, in load_checkpoint
    main_program=self.main_program)
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 367, in init_if_necessary
    if not self.load_checkpoint():
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 883, in finetune
    self.init_if_necessary()
  File "D:\Anaconda3\envs\test\lib\site-packages\paddlehub\finetune\task\base_task.py", line 868, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.8.0cpu\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < lookup_table > error]

**Comment by Steffy-zxf** [comment] 2020-06-01 06:42
你好！我这边还是没能复现你的错误。可以查看下，环境中的paddle以及paddlehub版本是否为最新版本。目前PaddlePaddle最新版本为1.8.1，PaddleHub最新版本为1.7.1
```shell
pip show paddlepaddle
pip show paddlehub
```

另外，方便提供下**最小**复现代码吗？

**Comment by lynette2020** [comment] 2020-06-01 06:54
我每次都是跑这些代码

import paddlehub as hub

module = hub.Module(name="senta_bilstm")
inputs, outputs, program = module.context(trainable=True)
dataset = hub.dataset.ChnSentiCorp()
reader = hub.reader.LACClassifyReader(
dataset=dataset,
vocab_path=module.get_vocab_path())

strategy = hub.AdamWeightDecayStrategy(
learning_rate=1e-5,
weight_decay=0.01,
warmup_proportion=0.1,
lr_scheduler="linear_decay",
)

config = hub.RunConfig(use_cuda=False, num_epoch=3, batch_size=32, strategy=strategy)

sent_feature = outputs["sentence_feature"]

feed_list = [inputs["words"].name]

cls_task = hub.TextClassifierTask(
data_reader=reader,
feature=sent_feature,
feed_list=feed_list,
num_classes=dataset.num_labels,
config=config)

cls_task.finetune_and_eval()

**Comment by lynette2020** [comment] 2020-06-01 06:58
我发现
cls_task = hub.TextClassifierTask(
data_reader=reader,
feature=sent_feature,
feed_list=feed_list,
num_classes=dataset.num_labels,
config=config)

完了之后会出现：

!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=4 # for example, set CPU_NUM as number of physical CPU core which is 4.

!!! The default number of CPU_NUM=1.

然后
cls_task.finetune_and_eval()
之后会报错：

Error Message Summary:
----------------------
InvalidArgumentError: Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] at (D:\1.8.1\paddle\paddle/fluid/framework/tensor_impl.h:33)
  [operator < lookup_table > error]

如果我在进入python之前 
set CPU_NUM=4

cls_task.finetune_and_eval()
之后会报错：
Error Message Summary:
----------------------
Error: Fail to allocate CPU memory: size = 644562944 .
  [Hint: p should not be null.] at (D:\1.8.1\paddle\paddle\fluid\memory\detail\system_allocator.cc:61)

**Comment by lynette2020** [comment] 2020-06-01 07:01
python==3.6.10

Package             Version
------------------- -------------------
appdirs             1.4.4
astor               0.8.1
Babel               2.8.0
certifi             2020.4.5.1
cfgv                3.1.0
chardet             3.0.4
click               7.1.2
cma                 3.0.3
colorama            0.4.3
colorlog            4.1.0
cycler              0.10.0
decorator           4.4.2
distlib             0.3.0
filelock            3.0.12
flake8              3.8.2
Flask               1.1.2
Flask-Babel         1.0.0
funcsigs            1.0.2
gast                0.3.3
graphviz            0.14
identify            1.4.18
idna                2.9
importlib-metadata  1.6.0
importlib-resources 1.5.0
itsdangerous        1.1.0
Jinja2              2.11.2
joblib              0.15.1
kiwisolver          1.2.0
MarkupSafe          1.1.1
matplotlib          2.2.4
mccabe              0.6.1
nltk                3.4
nodeenv             1.3.5
numpy               1.18.4
objgraph            3.4.1
opencv-python       4.2.0.34
paddlehub           1.7.1
paddlepaddle        1.8.1
pandas              1.0.4
pathlib             1.0.1
Pillow              7.1.2
pip                 20.0.2
pre-commit          2.4.0
prettytable         0.7.2
protobuf            3.12.2
pycodestyle         2.6.0
pyflakes            2.2.0
pyparsing           2.4.7
python-dateutil     2.8.1
pytz                2020.1
PyYAML              5.3.1
rarfile             3.1
regex               2020.5.14
requests            2.23.0
scipy               1.2.1
sentencepiece       0.1.91
setuptools          46.4.0.post20200518
singledispatch      3.4.0.3
six                 1.15.0
toml                0.10.1
tqdm                4.46.0
urllib3             1.25.9
virtualenv          20.0.21
visualdl            2.0.0b4
Werkzeug            1.0.1
wheel               0.34.2
wincertstore        0.2
yapf                0.26.0
zipp                3.1.0

**Comment by Steffy-zxf** [comment] 2020-06-01 11:51
你好！
> Error: Fail to allocate CPU memory: size = 644562944 .

这个错误是由于内存不够存放数据，可以试着降低batch_size。

另外 Tensor type的问题，我始终没能复现。你试试将paddlepaddle降级至1.6.2版本，paddlehub降级1.6.2，按照这样先运行。我这边尝试在别的windows机器上再复现下错误。

**Comment by haoyuying** [comment] 2021-04-14 12:48
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:48 UTC
