### ISSUE TITLE
human_pose_estimation_resnet50_mpii

### ISSUE THREAD

**Issue by zandls** [PaddlePaddle/PaddleFormers#716] opened 2020-06-23 06:25 UTC
请问这句话输出的这个地址我能获得吗，怎么获得可以指教一下吗，或者哪个keypoint_detection这个函数是公开的吗
![TIM图片20200623142021](https://user-images.githubusercontent.com/67177248/85368167-558b4d00-b55d-11ea-9588-cf79582d1b0c.jpg)

![TIM图片20200623142030](https://user-images.githubusercontent.com/67177248/85368205-6936b380-b55d-11ea-9cce-4cb561579bc6.jpg)

**Comment by nepeplwu** [comment] 2020-06-23 07:12
@zandls ，可以通过results里面的字段获取
```python
results = pose_estimation.keypoint_detection(
    images=[cv2.imread('/home/hutao/paddleone/01.png')], 
    output_dir='hhhhhhh', 
    visualization=True
)

# 获取所有结果的保存路径
paths = [result['path'] for result in results]
```
详细的api介绍见https://www.paddlepaddle.org.cn/hubdetail?name=human_pose_estimation_resnet50_mpii&en_category=KeyPointDetection

**Comment by haoyuying** [comment] 2021-04-14 12:33
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:33 UTC
