### ISSUE TITLE
ernie增量断点训练

### ISSUE THREAD

**Issue by x330930520** [PaddlePaddle/PaddleFormers#679] opened 2020-06-09 06:02 UTC
你好 已经迁移学习Fine-tune训练好了模型， 现在有新的数据需要做增量断点训练， 我之前训练的epoch是10， 然后增量数据接着训练把epoch调到比10大就会报错 请问这个该怎么解决呢

![15](https://user-images.githubusercontent.com/9064969/84111576-d58fbe00-aa59-11ea-9534-242dac0e37df.png)

**Comment by Steffy-zxf** [comment] 2020-06-09 08:19
你好！参考回复 https://github.com/PaddlePaddle/PaddleHub/issues/559#issuecomment-641114996

**Comment by haoyuying** [comment] 2021-04-14 12:39
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:39 UTC
