### ISSUE TITLE
Error: Getting 'tensor_desc' is not supported by the type of var _generated_var_0. 

### ISSUE THREAD

**Issue by AkiraZC** [PaddlePaddle/PaddleFormers#546] opened 2020-04-25 04:32 UTC
自定义组网函数时报错，train时没有问题，eval时报错，请问为什么？

self.unique_ids = fluid.layers.data(
    name="unique_ids", shape=[-1, 1], lod_level=0, dtype="int64")
_ = fluid.layers.assign(self.unique_ids)

fwd_cell = layers.GRUCell(hidden_size=1024)
fwd_output, _ = layers.rnn(cell=fwd_cell,inputs=self.feature,time_major=False,is_reverse=False)
bwd_cell = layers.GRUCell(hidden_size=1024)
bwd_output, _ = layers.rnn(cell=bwd_cell,inputs=self.feature,time_major=False,is_reverse=True)

logits = fluid.layers.fc(
    input=layers.concat(input=[fwd_output, bwd_output, self.feature], axis=2),
    size=2,
    num_flatten_dims=2,
    param_attr=fluid.ParamAttr(
        name="cls_seq_label_out_w",
        initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
    bias_attr=fluid.ParamAttr(
        name="cls_seq_label_out_b",
        initializer=fluid.initializer.Constant(0.)))

logits = fluid.layers.transpose(x=logits, perm=[2, 0, 1])
start_logits, end_logits = fluid.layers.unstack(x=logits, axis=0)

batch_ones = fluid.layers.fill_constant_batch_size_like(
    input=start_logits, dtype='int64', shape=[1], value=1)
num_seqs = fluid.layers.reduce_sum(input=batch_ones)

return [start_logits, end_logits, num_seqs]

**Comment by Steffy-zxf** [comment] 2020-04-25 08:17
你好！麻烦把环境信息（Paddle，PaddleHub，Python版本以及运行平台windows/Linux ）以及什么任务配合什么module运行说明清楚，方便我们复现以及排查问题。同时把报错堆栈信息粘贴完整。

**Comment by AkiraZC** [comment] 2020-04-25 08:51
您好，是在aistudio环境下运行的，python3.7, paddle1.6.2, paddlehub1.6.1，做阅读理解任务，我想试试在ernie的模型输出上再加一层双向GRU，就在ReadingComprehensionTask的基础上，在_build_net函数中添加了上述代码，结果模型可以train但是不能eval。

**Comment by AkiraZC** [comment] 2020-04-25 09:10
Traceback (most recent call last):
  File "train.py", line 67, in <module>
    reading_comprehension_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 864, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 885, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1103, in _run
    self._eval_interval_event()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 631, in hook_function
    func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 783, in _default_eval_interval_event
    self.eval(phase="dev")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 922, in eval
    run_states = self._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1054, in _run
    with fluid.program_guard(self.main_program, self.startup_program):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 508, in main_program
    self._build_env()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 410, in _build_env
    self.env.main_program, for_test=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 274, in clone_program
    dest_program.global_block())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 147, in _copy_vars_and_ops_in_blocks
    var_info = copy.deepcopy(get_variable_info(var))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 54, in get_variable_info
    'dtype': convert_dtype_to_string(var.dtype),
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1187, in dtype
    return self.desc.dtype()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::framework::VarDesc::tensor_desc() const
2   paddle::framework::VarDesc::GetDataType() const

----------------------
Error Message Summary:
----------------------
Error: Getting 'tensor_desc' is not supported by the type of var _generated_var_0. at (/paddle/paddle/fluid/framework/var_desc.cc:209)

**Comment by Steffy-zxf** [comment] 2020-05-15 08:11
这个问题我们正在修复，试试用dynamic_gru op。使用这个op，需要对输入去padding化。去padding化实现参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/paddlehub/finetune/task/sequence_task.py#L76

**Comment by haoyuying** [comment] 2021-04-14 12:44
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:44 UTC
