### ISSUE TITLE
用gpu预测时报cuda初始化错误

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/PaddleFormers#880] opened 2020-09-06 08:45 UTC
![image](https://user-images.githubusercontent.com/9254170/92321864-fb7c2d00-f05f-11ea-86f8-719f54979f2b.png)
在用flask搭建了服务，用gpu进行预测时会报上面cudu初始化的错误；用cpu的时候没有问题

**Comment by Steffy-zxf** [comment] 2020-09-07 01:42
你好！请问运行环境中paddle、paddlehub版本是多少？代码是什么样的呢？完成的错误堆栈信息是什么？

**Comment by haoyuying** [comment] 2021-04-14 12:00
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:00 UTC
Labels: installation
