### ISSUE TITLE
由通过强化学习处理不平衡数据。

### ISSUE THREAD

**Issue by lzb-James** [PaddlePaddle/PaddleFormers#869] opened 2020-09-02 02:08 UTC
# 处理故障分类问题
##  故障数据不平衡  会导致模型训练向多样本趋向
*  所以利用对抗学习生成少样本，让模型学习。数据是一维数据集。
有相关的代码或者类似的demo吗

**Comment by Steffy-zxf** [comment] 2020-09-03 01:55
你好！目前PaddleHub 不支持对抗样本学习。可以在 https://github.com/PaddlePaddle/models 看看是否有满足的模型demo。

**Comment by lzb-James** [comment] 2020-09-10 09:11
@Steffy-zxf Thk U I have receive it，but i find no demos like this
 

                                                                                         kind regards
                                                                                          Li-James

**Comment by haoyuying** [comment] 2021-04-14 12:05
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:05 UTC
Labels: feature
