### ISSUE TITLE
CentOS7.6  中  Fine-tune保存的模型转化为一个PaddleHub Module报错

### ISSUE THREAD

**Issue by zhuyingjun-zyj** [PaddlePaddle/PaddleFormers#731] opened 2020-07-03 08:27 UTC
输入命令：hub install /home/EmotionalAnalysis
（ /home/esoonProject/EmotionalAnalysis为路径）

报错：

Traceback (most recent call last):
  File "/usr/local/python3/bin/hub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/commands/install.py", line 54, in execute
    module_dir=argv[0], extra=extra)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/manager.py", line 197, in install_module
    module_name = hub.Module(directory=module_dir).name
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 104, in __new__
    module = cls.init_with_directory(directory=directory, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 199, in init_with_directory
    user_module = _item(directory=directory, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/module/module.py", line 145, in __init__
    self._initialize(**kwargs)
  File "/home/esoonProject/EmotionalAnalysis/module.py", line 92, in _initialize
    metrics_choices=metrics_choices)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 179, in __init__
    metrics_choices=metrics_choices)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 49, in __init__
    metrics_choices=metrics_choices)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 299, in __init__
    main_program, for_test=False)
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 274, in clone_program
    dest_program.global_block())
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 147, in _copy_vars_and_ops_in_blocks
    var_info = copy.deepcopy(get_variable_info(var))
  File "/usr/local/python3/lib/python3.7/site-packages/paddlehub/common/paddle_helper.py", line 65, in get_variable_info
    var_info['gradient_clip_attr'] = var.gradient_clip_attr
AttributeError: 'Parameter' object has no attribute 'gradient_clip_attr'
，希望老师帮忙解答一下

**Comment by Steffy-zxf** [comment] 2020-07-03 08:56
你好！ 请升级最新版本 paddle(1.8.0以上)和 paddlehub(1.7.0以上)。

**Comment by zhuyingjun-zyj** [comment] 2020-07-03 09:21
现在模型以及转好了，使用hub 启动 serving也成功了，但是出现了一下日志：

!!! The default number of CPU_NUM=1.
emotion == 1.0.0
 * Serving Flask app "paddlehub.serving.app_single" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-07-02 04:59:32,458-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)

上面的意思是：这样的部署方式不能用于工业环境，只能用于开发环境是嘛？如果是，怎么部署到工业环境呢？
希望老师帮忙解答一下

**Comment by ShenYuhan** [comment] 2020-07-03 09:33
您好，这个warning来自flask，是默认提示的，但一般情况下可以忽略。
如果想使用性能更好的web服务，可以启动时指定 use_multiprocess 即可使用wsgi框架gunicorn进行工业环境部署。
一般情况的使用，是可以忽略此问题的。

**Comment by haoyuying** [comment] 2021-04-14 12:30
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:30 UTC
