### ISSUE TITLE
是否支持fp16加速训练?

### ISSUE THREAD

**Issue by retfings** [PaddlePaddle/PaddleFormers#889] opened 2020-09-11 01:06 UTC
你好，是否有fp16加速训练API？

**Comment by Steffy-zxf** [comment] 2020-09-11 02:05
你好！你需要什么样的API进行fp16 加速？能说说任务背景吗？

**Comment by haoyuying** [comment] 2021-04-14 11:58
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:58 UTC
Labels: feature
