### ISSUE TITLE
有关paddlehub的autodl的问题，loss 和acc是一样的？？？

### ISSUE THREAD

**Issue by LilyCaiZL** [PaddlePaddle/PaddleFormers#641] opened 2020-05-28 05:26 UTC
为什么我用autodl的时候，跑出来的loss和acc是一样的值？同样的代码我放在aistudio上面，完全没问题，acc和loss是不一样的，acc大，loss就小很多，请问能否帮忙解决，我是昨天下的最新的paddlepaddle和paddlehub
`[2020-05-27 23:57:20,855] [   TRAIN] - step 3320 / 3429: loss=0.95312 acc=0.95312 [step/sec: 3.04]
[2020-05-27 23:57:24,215] [   TRAIN] - step 3330 / 3429: loss=0.96875 acc=0.96875 [step/sec: 3.04]
[2020-05-27 23:57:27,576] [   TRAIN] - step 3340 / 3429: loss=0.97188 acc=0.97188 [step/sec: 3.04]
[2020-05-27 23:57:31,104] [   TRAIN] - step 3350 / 3429: loss=0.98958 acc=0.98958 [step/sec: 3.00]
[2020-05-27 23:57:34,466] [   TRAIN] - step 3360 / 3429: loss=0.96250 acc=0.96250 [step/sec: 3.04]
[2020-05-27 23:57:37,835] [   TRAIN] - step 3370 / 3429: loss=0.97500 acc=0.97500 [step/sec: 3.03]
[2020-05-27 23:57:41,198] [   TRAIN] - step 3380 / 3429: loss=0.97813 acc=0.97813 [step/sec: 3.04]
[2020-05-27 23:57:44,691] [   TRAIN] - step 3390 / 3429: loss=0.96875 acc=0.96875 [step/sec: 3.25]
[2020-05-27 23:57:48,049] [   TRAIN] - step 3400 / 3429: loss=0.97813 acc=0.97813 [step/sec: 3.04]
[2020-05-27 23:57:51,471] [   TRAIN] - step 3410 / 3429: loss=0.97188 acc=0.97188 [step/sec: 2.99]
`

`==> round0/log-0.info <==
[2020-05-27 14:17:51,179] [    EVAL] - best model saved to ckpt_20200527140507/best_model [best acc=0.31413]
[2020-05-27 14:17:52,471] [    INFO] - Load the best model from ckpt_20200527140507/best_model
[2020-05-27 14:17:52,758] [    INFO] - Evaluation on test dataset start
[2020-05-27 14:17:56,026] [    EVAL] - [test dataset evaluation result] loss=0.39270 acc=0.39270 [step/sec: 5.92]
[2020-05-27 14:17:56,027] [    INFO] - Saving model checkpoint to ckpt_20200527140507/step_4100
[2020-05-27 14:17:57,099] [    INFO] - PaddleHub finetune finished.
[2020-05-27 14:17:57,100] [    INFO] - Try loading checkpoint from ckpt_20200527140507/ckpt.meta
[2020-05-27 14:17:57,397] [    INFO] - PaddleHub model checkpoint loaded. current_epoch=51, global_step=4100, best_score=0.31413
[2020-05-27 14:17:57,398] [    INFO] - Evaluation on dev dataset start
[2020-05-27 14:18:00,638] [    EVAL] - [dev dataset evaluation result] loss=0.31413 acc=0.31413 [step/sec: 5.97]

==> round0/log-10.info <==
[2020-05-27 18:05:31,993] [    EVAL] - best model saved to ckpt_20200527172834/best_model [best acc=0.83658]
[2020-05-27 18:05:33,126] [    INFO] - Load the best model from ckpt_20200527172834/best_model
[2020-05-27 18:05:33,401] [    INFO] - Evaluation on test dataset start
[2020-05-27 18:05:36,953] [    EVAL] - [test dataset evaluation result] loss=0.88527 acc=0.88527 [step/sec: 2.60]
[2020-05-27 18:05:36,954] [    INFO] - Saving model checkpoint to ckpt_20200527172834/step_5075
[2020-05-27 18:05:37,949] [    INFO] - PaddleHub finetune finished.
[2020-05-27 18:05:37,949] [    INFO] - Try loading checkpoint from ckpt_20200527172834/ckpt.meta
[2020-05-27 18:05:38,226] [    INFO] - PaddleHub model checkpoint loaded. current_epoch=146, global_step=5075, best_score=0.83658
[2020-05-27 18:05:38,226] [    INFO] - Evaluation on dev dataset start
[2020-05-27 18:05:41,438] [    EVAL] - [dev dataset evaluation result] loss=0.83658 acc=0.83658 [step/sec: 2.90]
`

**Comment by Steffy-zxf** [comment] 2020-05-28 07:49
你好！
> 为什么我用autodl的时候，跑出来的loss和acc是一样的值？同样的代码我放在aistudio上面，完全没问题，acc和loss是不一样的，acc大，loss就小很多

上面说的情况是指，在本地机器上使用autodl优化超参，出现 acc和loss结果一致。但是在aistudio上使用autodl优化超参，出现acc和loss不同？ 是指这个情况吗？

另外，请先对齐本地和aistudio上的paddle版本和paddlehub版本。同时我想看看，你的超参优化脚本train.py 和 待优化超参数文件yml文件是什么样的？

**Comment by haoyuying** [comment] 2021-04-14 12:48
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:48 UTC
