### ISSUE TITLE
Module yolov3_darknet53_venus is not executable

### ISSUE THREAD

**Issue by mingzhanliao** [PaddlePaddle/PaddleFormers#584] opened 2020-05-11 09:22 UTC
Module yolov3_darknet53_venus is not executable 

paddlepaddle = 1.6.2

paddlehub = 1.6.0

**Comment by Steffy-zxf** [comment] 2020-05-11 12:51
你好！yolov3_darknet53_venus module没有相应的类别标签，所以不能直接预测。故出现上述提示`Module yolov3_darknet53_venus is not executable`

**Comment by mingzhanliao** [comment] 2020-05-12 08:24
那它是可以使用的吗

**Comment by Steffy-zxf** [comment] 2020-05-12 09:54
yolov3_darknet53_venus支持Fine-tune，PaddleHub未来会支持目标检测任务Fine-tune

**Comment by haoyuying** [comment] 2021-04-14 12:54
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:54 UTC
