### ISSUE TITLE
senta-bilstm在进行迁移训练时报错

### ISSUE THREAD

**Issue by BledCao** [PaddlePaddle/PaddleFormers#734] opened 2020-07-04 05:46 UTC
您好，请教下，我本来是想按自己的数据集迁移训练模型，但是运行以下代码后总是报错，是因为hub的安装路径和Anaconda的安装路径不同导致的吗？求解~

paddlehub1.7.1
系统：windows python 3.6.1
运行代码：
import paddlehub as hub
module = hub.Module(name="senta_bilstm")
inputs, outputs, program = module.context(trainable=True)
from paddlehub.dataset.base_nlp_dataset import BaseNLPDataset

class DemoDataset(BaseNLPDataset):
    def __init__(self):
        # 数据集存放位置
        self.dataset_dir = "C:/Users/ccb/data/"
        super(DemoDataset, self).__init__(
            base_path=self.dataset_dir,
            train_file="train.tsv",
            dev_file="dev.tsv",
            test_file="test.tsv",
            # 如果还有预测数据（不需要文本类别label），可以放在predict.tsv
            #predict_file="predict.tsv",
            train_file_with_header=True,
            dev_file_with_header=True,
            test_file_with_header=True,
            #predict_file_with_header=True,
            # 数据集类别集合
            label_list=["0", "1"])
dataset = DemoDataset()
reader = hub.reader.LACClassifyReader(
    dataset=dataset,
    vocab_path=module.get_vocab_path())
strategy = hub.AdamWeightDecayStrategy(
    learning_rate=1e-5,
    weight_decay=0.01,
    warmup_proportion=0.1,
    lr_scheduler="linear_decay",
)

config = hub.RunConfig(use_cuda=False, num_epoch=3, batch_size=8, strategy=strategy)
sent_feature = outputs["sentence_feature"]

feed_list = [inputs["words"].name]

cls_task = hub.TextClassifierTask(
    data_reader=reader,
    feature=sent_feature,
    feed_list=feed_list,
    num_classes=dataset.num_labels,
    config=config)
run_states = cls_task.finetune_and_eval()

运行后报错信息：
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the scale Op's Input Variable X(@HUB_senta_bilstm@fc_12.w_0) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (D:\1.8.1\paddle\paddle\fluid\framework\operator.cc:1289)
  [operator < scale > error]

**Comment by BledCao** [comment] 2020-07-04 08:02
https://aistudio.baidu.com/bdcpu6/user/323793/612284/notebooks/612284.ipynb
在AI studio上也报错，但错误信息还不一样

**Comment by Steffy-zxf** [comment] 2020-07-05 05:44
你好！
>  https://aistudio.baidu.com/bdcpu6/user/323793/612284/notebooks/612284.ipynb

是私密状态，无法查看。

关于senta 迁移学习，可以参考教程：https://aistudio.baidu.com/aistudio/projectdetail/216846

**Comment by BledCao** [comment] 2020-07-20 16:48
您好 设为公开了

**Comment by Steffy-zxf** [comment] 2020-07-21 01:58
@BledCao 公开的项目链接方便贴下吗？

**Comment by BledCao** [comment] 2020-07-22 15:29
https://aistudio.baidu.com/aistudio/projectdetail/612284
谢谢

**Comment by Steffy-zxf** [comment] 2020-07-25 11:05
@BledCao 你好！根据你公开的项目
> https://aistudio.baidu.com/aistudio/projectdetail/612284

![image](https://user-images.githubusercontent.com/48793257/88455615-57706500-cea9-11ea-8f91-679d1a3d70cb.png)

![image](https://user-images.githubusercontent.com/48793257/88455610-4de6fd00-cea9-11ea-9fee-eb11e42a3ed5.png)

上述错误是因为，代码中调用了两遍context接口导致的。context接口调用一遍即可，所以删去上述图片中的一处context接口调用即可。

**Comment by haoyuying** [comment] 2021-04-14 12:30
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:30 UTC

**Comment by liqingyang665** [comment] 2022-08-21 08:46
请问用自己的数据集的问题解决了吗？
