### ISSUE TITLE
paddlehub保存infer模型时使用默认参数,但是找不到__model__?

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/PaddleFormers#934] opened 2020-09-28 10:59 UTC
所以我该怎么样部署aistudio的沙盒？
https://ai.baidu.com/ai-doc/AISTUDIO/bk3e382cq
![image](https://user-images.githubusercontent.com/42665925/94424372-b1005300-01bc-11eb-9bf1-3b85c08698f5.png)

**Comment by Steffy-zxf** [comment] 2020-10-03 00:45
你好！请问你是怎么保存的模型？使用哪个接口？

**Comment by haoyuying** [comment] 2021-04-14 11:49
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:49 UTC
