### ISSUE TITLE
加载finetune好的senta-bilstm模型跑预测，第一次preditct正常，第二次preditct报错

### ISSUE THREAD

**Issue by yocen** [PaddlePaddle/PaddleFormers#509] opened 2020-04-10 03:51 UTC
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.6.1，PaddlePaddle1.7.1
2）系统环境：AI STUDIO高级版
- 复现信息：
加载finetune好的senta-bilstm模型跑task.predict，首次运行task.predict正常，紧接着更改预测数据再跑task.predict，会报错，必须重启notebook重新加载模型才能再跑预测。
项目地址：https://aistudio.baidu.com/aistudio/projectdetail/311069
错误信息：
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-4-7d1f4e42a9ac> in <module>
      6 run_states = cls_task.predict(
      7     data=data,
----> 8     accelerate_mode=False)
      9 
     10 results = [run_state.run_results for run_state in run_states]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in predict(self, data, load_best_model, return_result, accelerate_mode)
   1014                 self.init_if_necessary()
   1015             if not self.accelerate_mode:
-> 1016                 run_states = self._run()
   1017             else:
   1018                 if not self._predictor:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1072             period_run_states = []
   1073 
-> 1074             for run_step, batch in enumerate(data_reader(), start=1):
   1075                 step_run_state = RunState(len(self.fetch_list))
   1076                 step_run_state.run_step = 1
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py in __reader_creator__()
    494                     item.append(batch)
    495                     if len(item) == num:
--> 496                         yield list(self.feed_parallel(item, num))
    497                         item = []
    498                 if not drop_last and len(item) != 0:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py in feed_parallel(self, iterable, num_places)
    407         for p, batch in six.moves.zip(places, iterable):
    408             self.place = p
--> 409             yield self.feed(batch)
    410         self.place = place
    411 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py in feed(self, iterable)
    328         for each_name, each_converter in six.moves.zip(self.feed_names,
    329                                                        converter):
--> 330             ret_dict[each_name] = each_converter.done()
    331         return ret_dict
    332 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py in done(self)
    137 
    138     def done(self):
--> 139         arr = numpy.array(self.data, dtype=self.dtype)
    140         if self.shape:
    141             if len(arr.shape) != len(self.shape):
ValueError: invalid literal for int() with base 10: '酒'

**Comment by kinghuin** [comment] 2020-04-10 07:58
@yocen Hi,感谢反馈bug，我们将在下个版本修复。请暂时使用以下方式：
修改
```python
reader = hub.reader.LACClassifyReader(
    dataset=dataset,     
    vocab_path=module.get_vocab_path())
```
为
```python
class MyLACClassifyReader(hub.reader.LACClassifyReader):
    def data_generator(self,
                       batch_size=1,
                       phase="train",
                       shuffle=False,
                       data=None,
                       return_list=True):
        if phase=="predict":
            self.has_processed[phase]=False
        return super(MyLACClassifyReader, self).data_generator(batch_size,phase,shuffle,data,return_list)
reader = MyLACClassifyReader(
    dataset=dataset,     
    vocab_path=module.get_vocab_path())
```

**Comment by haoyuying** [comment] 2021-04-14 12:46
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:46 UTC
