### ISSUE TITLE
deeplabv3p_xception65_humanseg实现抠图

### ISSUE THREAD

**Issue by zandls** [PaddlePaddle/PaddleFormers#707] opened 2020-06-20 03:31 UTC
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddleHub版本是1.7.1
paddlepaddle-GPU版本是1.8.1.post97
系统：Ubuntu16.04  python3.6
![11](https://user-images.githubusercontent.com/67177248/85190306-ba3e7180-b2e9-11ea-9cc3-3128781465d0.jpg)
 File "/home/hutao/paddleone/livingbody-AutoCutout-5517359f03aad59c97f784bf06ef343d086173de/AutoCutout/upload_pictures.py", line 43, in upload
    convert(basepath, upload_path)
  File "/home/hutao/paddleone/livingbody-AutoCutout-5517359f03aad59c97f784bf06ef343d086173de/AutoCutout/upload_pictures.py", line 56, in convert
    results = eval(r.json()["results"])
File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by Steffy-zxf** [comment] 2020-06-21 07:56
你好！根据以上错误提示，应该是你的代码写法语法上有问题。

**Comment by haoyuying** [comment] 2021-04-14 12:34
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:34 UTC
