### ISSUE TITLE
OCR报错

### ISSUE THREAD

**Issue by j2538318409** [PaddlePaddle/PaddleFormers#890] opened 2020-09-11 07:28 UTC
TypeError: float() argument must be a string or a number, not '_NoValueType'

**Comment by Steffy-zxf** [comment] 2020-09-15 01:44
你好！方便给出完整的错误信息吗，以及最小复现代码？

**Comment by haoyuying** [comment] 2021-04-14 11:58
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:58 UTC
Labels: cv
