### ISSUE TITLE
paddlehub pip安装成功，但是paddlehub依赖的paddle却没有进行自动安装，requirements.txt缺paddle啊

### ISSUE THREAD

**Issue by plume** [PaddlePaddle/PaddleFormers#828] opened 2020-08-18 08:15 UTC
D:\anaconda3\Scripts>pip install --upgrade paddlehub
Requirement already up-to-date: paddlehub in d:\anaconda3\lib\site-packages (1.8.1)
Requirement already satisfied, skipping upgrade: flake8 in d:\anaconda3\lib\site-packages (from paddlehub) (3.8.3)
Requirement already satisfied, skipping upgrade: yapf==0.26.0 in d:\anaconda3\lib\site-packages (from paddlehub) (0.26.0)
Requirement already satisfied, skipping upgrade: sentencepiece in d:\anaconda3\lib\site-packages (from paddlehub) (0.1.91)
Requirement already satisfied, skipping upgrade: pre-commit in d:\anaconda3\lib\site-packages (from paddlehub) (2.6.0)
Requirement already satisfied, skipping upgrade: colorlog in d:\anaconda3\lib\site-packages (from paddlehub) (4.2.1)
Requirement already satisfied, skipping upgrade: nltk in d:\anaconda3\lib\site-packages (from paddlehub) (3.4)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in d:\anaconda3\lib\site-packages (from paddlehub) (1.12.0)
Requirement already satisfied, skipping upgrade: pandas; python_version >= "3" in d:\anaconda3\lib\site-packages (from paddlehub) (0.24.2)
Requirement already satisfied, skipping upgrade: visualdl>=2.0.0b in d:\anaconda3\lib\site-packages (from paddlehub) (2.0.0)
Requirement already satisfied, skipping upgrade: flask>=1.1.0 in d:\anaconda3\lib\site-packages (from paddlehub) (1.1.2)
Requirement already satisfied, skipping upgrade: tqdm in d:\anaconda3\lib\site-packages (from paddlehub) (4.31.1)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.0 in d:\anaconda3\lib\site-packages (from paddlehub) (3.8.0)
Requirement already satisfied, skipping upgrade: cma>=2.7.0 in d:\anaconda3\lib\site-packages (from paddlehub) (3.0.3)
Requirement already satisfied, skipping upgrade: pyflakes<2.3.0,>=2.2.0 in d:\anaconda3\lib\site-packages (from flake8->paddlehub) (2.2.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in d:\anaconda3\lib\site-packages (from flake8->paddlehub) (1.7.0)
Requirement already satisfied, skipping upgrade: pycodestyle<2.7.0,>=2.6.0a1 in d:\anaconda3\lib\site-packages (from flake8->paddlehub) (2.6.0)
Requirement already satisfied, skipping upgrade: mccabe<0.7.0,>=0.6.0 in d:\anaconda3\lib\site-packages (from flake8->paddlehub) (0.6.1)
Requirement already satisfied, skipping upgrade: pyyaml>=5.1 in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (5.1)
Requirement already satisfied, skipping upgrade: nodeenv>=0.11.1 in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (1.4.0)
Requirement already satisfied, skipping upgrade: cfgv>=2.0.0 in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (3.2.0)
Requirement already satisfied, skipping upgrade: toml in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (0.10.1)
Requirement already satisfied, skipping upgrade: identify>=1.0.0 in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (1.4.28)
Requirement already satisfied, skipping upgrade: virtualenv>=20.0.8 in d:\anaconda3\lib\site-packages (from pre-commit->paddlehub) (20.0.27)
Requirement already satisfied, skipping upgrade: colorama; sys_platform == "win32" in d:\anaconda3\lib\site-packages (from colorlog->paddlehub) (0.4.1)
Requirement already satisfied, skipping upgrade: singledispatch in d:\anaconda3\lib\site-packages (from nltk->paddlehub) (3.4.0.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in d:\anaconda3\lib\site-packages (from pandas; python_version >= "3"->paddlehub) (2.8.0)
Requirement already satisfied, skipping upgrade: pytz>=2011k in d:\anaconda3\lib\site-packages (from pandas; python_version >= "3"->paddlehub) (2018.9)
Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in d:\anaconda3\lib\site-packages (from pandas; python_version >= "3"->paddlehub) (1.16.2)
Requirement already satisfied, skipping upgrade: requests in d:\anaconda3\lib\site-packages (from visualdl>=2.0.0b->paddlehub) (2.21.0)
Requirement already satisfied, skipping upgrade: opencv-python in d:\anaconda3\lib\site-packages (from visualdl>=2.0.0b->paddlehub) (3.4.2.16)
Requirement already satisfied, skipping upgrade: Pillow>=7.0.0 in d:\anaconda3\lib\site-packages (from visualdl>=2.0.0b->paddlehub) (7.2.0)
Requirement already satisfied, skipping upgrade: Flask-Babel>=1.0.0 in d:\anaconda3\lib\site-packages (from visualdl>=2.0.0b->paddlehub) (1.0.0)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.15 in d:\anaconda3\lib\site-packages (from flask>=1.1.0->paddlehub) (1.0.1)
Requirement already satisfied, skipping upgrade: click>=5.1 in d:\anaconda3\lib\site-packages (from flask>=1.1.0->paddlehub) (7.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in d:\anaconda3\lib\site-packages (from flask>=1.1.0->paddlehub) (2.11.2)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in d:\anaconda3\lib\site-packages (from flask>=1.1.0->paddlehub) (1.1.0)
Requirement already satisfied, skipping upgrade: setuptools in d:\anaconda3\lib\site-packages (from protobuf>=3.6.0->paddlehub) (40.8.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in d:\anaconda3\lib\site-packages (from importlib-metadata; python_version < "3.8"->flake8->paddlehub) (3.1.
Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in d:\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub) (1.4.4)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.1 in d:\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub) (0.3.1)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in d:\anaconda3\lib\site-packages (from virtualenv>=20.0.8->pre-commit->paddlehub) (3.0.10)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in d:\anaconda3\lib\site-packages (from requests->visualdl>=2.0.0b->paddlehub) (2.8)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests->visualdl>=2.0.0b->paddlehub) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in d:\anaconda3\lib\site-packages (from requests->visualdl>=2.0.0b->paddlehub) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests->visualdl>=2.0.0b->paddlehub) (2019.3.9)
Requirement already satisfied, skipping upgrade: Babel>=2.3 in d:\anaconda3\lib\site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0b->paddlehub) (2.6.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in d:\anaconda3\lib\site-packages (from Jinja2>=2.10.1->flask>=1.1.0->paddlehub) (1.1.1)

D:\anaconda3\Scripts>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\Lib\site-packages\paddlehub\__init__.py", line 27, in <module>
    from . import module
  File "D:\anaconda3\Lib\site-packages\paddlehub\module\__init__.py", line 16, in <module>
    from . import module
  File "D:\anaconda3\Lib\site-packages\paddlehub\module\module.py", line 28, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'paddle'
>>>

**Comment by Steffy-zxf** [comment] 2020-08-18 08:55
你好！Paddle需要用户自行安装。paddle安装参考：https://www.paddlepaddle.org.cn/install/quick

**Comment by haoyuying** [comment] 2021-04-14 12:16
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:16 UTC
Labels: installation
