### ISSUE TITLE
hub 快速体验出现错误 

### ISSUE THREAD

**Issue by oneofsummer** [PaddlePaddle/PaddleFormers#849] opened 2020-08-25 15:32 UTC
hub run pyranidbox_Iite_nobile_nask.-input_path test_nask_detection.jpg -visualization=True--output_dir='detection_result'

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
File " /usr/local/python2.7.15/bin/hub" , line 11,in <module>
sys.exit(main()
File " /usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/connands/hub.py"，line 64，in main
CORmand.execute(argv[1:]）
File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/conmands/hub.py"，line 51，in execute
return command.execute(argv[1:]
File"/usr/local/python2.7.1i5/lib/python2.7/site-packages/paddlehub/conpands/run.py"，line 242，in execute
resuits ' self.module.run_func(argv[1:]）
File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/nodule/nodule.py"，line 59,in _rapper
return func(*args，**kwargs）
File "/root/.paddlehub/nodules/pyramidbox_lite_nobile_nask/nodule.py"，line 259，in run_cnd
confs_threshold=args.confs_threshold)
File " /root/.paddlehub/nodules/pyranidbox_lite_nobile_mask/nodule.py",line 128,in face_detection
images, paths, use_gpu，use_multi_scale):
File"/root/.paddlehub/nodules/pyramidbox_lite_nobile_mask/data_feed.py" ，line 202，in reader
confs_threshold=confs_threshoid)
File "/root/.paddlehub/modules/pyranidbox_lite_nobile/module.py" ，line 101，in face_detection
for element in reader(images, paths,shrink):.
File "/root/.paddlehub/modules/pyranidbox_lite_nobile/data_feed.py"，line 67，in reader
'image_width'] = preprocess(element[ 'org_im']， shrink)
File "]root/.paddlehub/nodules/pyranidbox_lite_nobile/data_feed.py"，line 19，in preprocess
cv2.INTER_NEAREST)
TypeError: Expected Ptr<cv::UMat> for argument 'dst'
入d98sed7f7b47/hone hub run pyranidbox_lite_gobile_gask.-iput_path test_mask_detection.jg vistaliztion=7ue .output_dird'detection_resilt

**Comment by oneofsummer** [comment] 2020-08-25 15:39
> hub run pyranidbox_Iite_nobile_nask.-input_path test_nask_detection.jpg -visualization=True--output_dir='detection_result'
> 
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> Traceback (most recent call last):
> File " /usr/local/python2.7.15/bin/hub" , line 11,in
> sys.exit(main()
> File " /usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/connands/hub.py"，line 64，in main
> CORmand.execute(argv[1:]）
> File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/conmands/hub.py"，line 51，in execute
> return command.execute(argv[1:]
> File"/usr/local/python2.7.1i5/lib/python2.7/site-packages/paddlehub/conpands/run.py"，line 242，in execute
> resuits ' self.module.run_func(argv[1:]）
> File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/nodule/nodule.py"，line 59,in _rapper
> return func(*args，**kwargs）
> File "/root/.paddlehub/nodules/pyramidbox_lite_nobile_nask/nodule.py"，line 259，in run_cnd
> confs_threshold=args.confs_threshold)
> File " /root/.paddlehub/nodules/pyranidbox_lite_nobile_mask/nodule.py",line 128,in face_detection
> images, paths, use_gpu，use_multi_scale):
> File"/root/.paddlehub/nodules/pyramidbox_lite_nobile_mask/data_feed.py" ，line 202，in reader
> confs_threshold=confs_threshoid)
> File "/root/.paddlehub/modules/pyranidbox_lite_nobile/module.py" ，line 101，in face_detection
> for element in reader(images, paths,shrink):.
> File "/root/.paddlehub/modules/pyranidbox_lite_nobile/data_feed.py"，line 67，in reader
> 'image_width'] = preprocess(element[ 'org_im']， shrink)
> File "]root/.paddlehub/nodules/pyranidbox_lite_nobile/data_feed.py"，line 19，in preprocess
> cv2.INTER_NEAREST)
> TypeError: Expected Ptrcv::UMat for argument 'dst'

**Comment by livingbody** [comment] 2020-08-25 16:50
建议使用python3.5以上版本



---原始邮件---
发件人: "oneofsummer"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 晚上11:32
收件人: "PaddlePaddle/PaddleHub"<PaddleHub@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PaddlePaddle/PaddleHub] hub 快速体验出现错误  (#849)




 
hub run pyranidbox_Iite_nobile_nask.-input_path test_nask_detection.jpg -visualization=True--output_dir='detection_result'
 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
 Traceback (most recent call last):
 File " /usr/local/python2.7.15/bin/hub" , line 11,in 
 sys.exit(main()
 File " /usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/connands/hub.py"，line 64，in main
 CORmand.execute(argv[1:]）
 File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/conmands/hub.py"，line 51，in execute
 return command.execute(argv[1:]
 File"/usr/local/python2.7.1i5/lib/python2.7/site-packages/paddlehub/conpands/run.py"，line 242，in execute
 resuits ' self.module.run_func(argv[1:]）
 File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddlehub/nodule/nodule.py"，line 59,in _rapper
 return func(*args，**kwargs）
 File "/root/.paddlehub/nodules/pyramidbox_lite_nobile_nask/nodule.py"，line 259，in run_cnd
 confs_threshold=args.confs_threshold)
 File " /root/.paddlehub/nodules/pyranidbox_lite_nobile_mask/nodule.py",line 128,in face_detection
 images, paths, use_gpu，use_multi_scale):
 File"/root/.paddlehub/nodules/pyramidbox_lite_nobile_mask/data_feed.py" ，line 202，in reader
 confs_threshold=confs_threshoid)
 File "/root/.paddlehub/modules/pyranidbox_lite_nobile/module.py" ，line 101，in face_detection
 for element in reader(images, paths,shrink):.
 File "/root/.paddlehub/modules/pyranidbox_lite_nobile/data_feed.py"，line 67，in reader
 'image_width'] = preprocess(element[ 'org_im']， shrink)
 File "]root/.paddlehub/nodules/pyranidbox_lite_nobile/data_feed.py"，line 19，in preprocess
 cv2.INTER_NEAREST)
 TypeError: Expected Ptrcv::UMat for argument 'dst'
 入d98sed7f7b47/hone hub run pyranidbox_lite_gobile_gask.-iput_path test_mask_detection.jg vistaliztion=7ue .output_dird'detection_resilt

**Comment by haoyuying** [comment] 2020-08-26 04:42
欢迎您对PaddleHub提出建议，非常感谢您对PaddleHub的贡献！
建议使用python3.7，opencv-python使用4.2.0.34，paddlepaddle >= 1.6.2, paddlehub >= 1.6.0，即可快速体验模型。

**Comment by haoyuying** [comment] 2021-04-14 12:09
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:09 UTC
Labels: cv
