### ISSUE TITLE
口罩检测模型报错

### ISSUE THREAD

**Issue by zengqi0730** [PaddlePaddle/PaddleFormers#609] opened 2020-05-18 03:54 UTC
paddlepaddle-gpu       1.7.0.post107 
paddlehub：1.6.2
pyramidbox_lite_mobile_mask:1.3.0
paddleslim             1.0.1 

-----------------------------------------------------------------------------------------------------
import paddlehub as hub
import cv2

mask_detector = hub.Module(name="pyramidbox_lite_mobile_mask")
print(mask_detector.version)
img = cv2.imread('/home/edu/Desktop/1.jpg')
print(img.shape)
result = mask_detector.face_detection(images=[img],data=None)

------------------------------------------------------------------------------------------------------
[2020-05-18 11:35:10,849] [    INFO] - Installing pyramidbox_lite_mobile_mask module
[2020-05-18 11:35:10,913] [    INFO] - Module pyramidbox_lite_mobile_mask already installed in /home/edu/.paddlehub/modules/pyramidbox_lite_mobile_mask
[2020-05-18 11:35:10,913] [    INFO] - Installing pyramidbox_lite_mobile module
[2020-05-18 11:35:10,917] [    INFO] - Module pyramidbox_lite_mobile already installed in /home/edu/.paddlehub/modules/pyramidbox_lite_mobile
1.3.0
(667, 500, 3)
Traceback (most recent call last):
  File "/home/edu/PycharmProjects/paddledemo/zengqi.py", line 300, in <module>
    result = mask_detector.face_detection(images=[img],data=None)
  File "/home/edu/.paddlehub/modules/pyramidbox_lite_mobile_mask/module.py", line 127, in face_detection
    images, paths, use_gpu, use_multi_scale):
  File "/home/edu/.paddlehub/modules/pyramidbox_lite_mobile_mask/data_feed.py", line 202, in reader
    confs_threshold=confs_threshold)
TypeError: __call__() missing 1 required positional argument: 'data'

Process finished with exit code 1

口罩模型起不来，请帮忙看下问题

**Comment by Steffy-zxf** [comment] 2020-05-18 07:58
你好！根据错误提示，应该是你的pyramidbox_lite_mobile_mask是旧版本，但是预测时候用的预测接口是新版本使用方式。解决方法：

```python
hub install pyramidbox_lite_mobile_mask==1.3.0
hub install pyramidbox_lite_mobile==1.2.0
```

关于module的版本信息参见官网介绍：https://www.paddlepaddle.org.cn/hubdetail?name=pyramidbox_lite_mobile_mask&en_category=ObjectDetection

![image](https://user-images.githubusercontent.com/48793257/82188302-4262dd00-9920-11ea-8ed3-435e7b48594f.png)

**Comment by haoyuying** [comment] 2021-04-14 12:51
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:51 UTC
