### ISSUE TITLE
PaddleHubOcr   chinese_ocr_db_crnn_mobile预测一张图片需要时间很久，有什么办法解决吗？result=ocr.recognize_text(images=[cv2.imread('/PATH/TO/IMAGE')], text_thresh=0.5) 这行代码的执行时间需要很久

### ISSUE THREAD

**Issue by WJinhai** [PaddlePaddle/PaddleFormers#722] opened 2020-06-28 07:09 UTC
每次运行的时候都有这两行，能否放在程序启动的时候，这样不需要每次运行都去加载模型
[2020-06-28 15:27:07,018] [ INFO] - Installing chinese_text_detection_db_server module
[2020-06-28 15:27:07,019] [ INFO] - Module chinese_text_detection_db_server already installed in /home/image/.paddlehub/modules/chinese_text_detection_db_server

**Comment by WJinhai** [comment] 2020-06-28 07:29
每次运行的时候都有这两行，能否放在程序启动的时候，这样不需要每次运行都去加载模型
[2020-06-28 15:27:07,018] [    INFO] - Installing chinese_text_detection_db_server module
[2020-06-28 15:27:07,019] [    INFO] - Module chinese_text_detection_db_server already installed in /home/image/.paddlehub/modules/chinese_text_detection_db_server

**Comment by Steffy-zxf** [comment] 2020-06-28 09:09
你好！你的预测代码是怎么写的？预测只需要加载一次module，之后调用预测接口既可完成预测。

**Comment by haoyuying** [comment] 2021-04-14 12:31
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:31 UTC
