### ISSUE TITLE
安装paddlehub报错

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/PaddleFormers#813] opened 2020-08-09 08:09 UTC
- PaddlePaddle = 1.7.2 python 3.7.5
- 系统环境：
![sys](https://user-images.githubusercontent.com/20811685/89727789-6edb5080-da5a-11ea-8434-407788b99a2e.png)
- 报错：
![debug](https://user-images.githubusercontent.com/20811685/89727783-671bac00-da5a-11ea-99d8-6d0267a73187.png)

**Comment by kinghuin** [comment] 2020-08-10 02:12
Hi, 我无法复现这一问题。看起来是sentencepiece的安装出现了问题，请尝试
```
pip install sentencepiece
```
如果安装失败，尝试更换源。

**Comment by kinghuin** [comment] 2020-08-10 02:29
和系统环境可能也有关系，可以参考
https://github.com/google/sentencepiece/issues/378

**Comment by malamasn** [comment] 2020-10-28 09:24
```pip install sentencepiece==0.1.82``` worked for me, I have Python 3.7.5 too

**Comment by haoyuying** [comment] 2021-04-14 12:17
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:17 UTC
Labels: installation

**Comment by sinisarudan** [comment] 2022-08-02 09:04
> 和系统环境可能也有关系，可以参考 [google/sentencepiece#378](https://github.com/google/sentencepiece/issues/378)

thanks, for this. This prolonged my life for few more hours :)
