### ISSUE TITLE
RuntimeError: Can't find module retake_efficientnetb7_finetuned, please check your spelling.

### ISSUE THREAD

**Issue by yisampi** [PaddlePaddle/PaddleFormers#534] opened 2020-04-22 06:05 UTC
Fine-tune保存的模型安装后，无法找到该模型

保存模型
$ hub install finetuned_model_to_module                                        
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=28 # for example, set CPU_NUM as number of physical CPU core which is 28.

!!! The default number of CPU_NUM=1.
Module retake_efficientnetb7_finetuned-1.0.0 already installed in /home/sam.yi/.paddlehub/modules/retake_efficientnetb7_finetuned
(reverse-i-search)`star': hub serving ^Cart 

该模型已经保存
ls /home/sam.yi/.paddlehub/modules/retake_efficientnetb7_finetuned -ld
drwxrwxr-x 4 sam.yi sam.yi 130 Apr 22 10:49 /home/sam.yi/.paddlehub/modules/retake_efficientnetb7_finetuned

hub serving该模型时 找不到retake_efficientnetb7_finetuned
$ hub serving start -m retake_efficientnetb7_finetuned
Traceback (most recent call last):
  File "/optanaconda3/envs/paddlepaddle/bin/hub", line 10, in <module>
    sys.exit(main())
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 64, in main
    command.execute(argv[1:])
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/hub.py", line 51, in execute
    return command.execute(argv[1:])
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 426, in execute
    self.start_serving()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 373, in start_serving
    self.start_single_app_with_args()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 288, in start_single_app_with_args
    self.preinstall_modules()
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/commands/serving.py", line 207, in preinstall_modules
    m = hub.Module(**init_args)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/module/module.py", line 102, in __new__
    name=name, version=version, **kwargs)
  File "/home/sam.yi/.local/lib/python3.7/site-packages/paddlehub/module/module.py", line 173, in init_with_name
    raise RuntimeError(tips)
RuntimeError: Can't find module retake_efficientnetb7_finetuned, please check your spelling.

paddlehub                          1.6.1       
paddlepaddle-gpu                   1.7.1.post97

**Comment by nepeplwu** [comment] 2020-04-22 07:22
@yisampi ，感谢反馈，retake_efficientnetb7_finetuned是否方便发给我们看下？

**Comment by yisampi** [comment] 2020-04-22 13:34
@nepeplwu 

 $ ls retake_efficientnetb7_finetuned
cv_finetune_turtorial_demo_ULMFiTStrategy  __init__.py  module.py  mydataset.py  __pycache__
 
 $ ls retake_efficientnetb7_finetuned/cv_finetune_turtorial_demo_ULMFiTStrategy/
best_model  ckpt.meta

是这个不 ？

**Comment by nepeplwu** [comment] 2020-04-23 15:23
@yisampi ，不是，是`/home/sam.yi/.paddlehub/modules/retake_efficientnetb7_finetuned`整个目录打包发下，怀疑是代码哪里写错了

**Comment by haoyuying** [comment] 2021-04-14 12:44
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:44 UTC
