### ISSUE TITLE
请问paddle1.8怎么调用Bi_lstm的接口呢，官方文档没有

### ISSUE THREAD

**Issue by Masterkmp** [PaddlePaddle/PaddleFormers#907] opened 2020-09-19 09:14 UTC
paddlehub中如何调用BiLSTM进行组网？

**Comment by Steffy-zxf** [comment] 2020-09-20 01:48
你好！BiLSTM属于在paddlehub预置网络模块中。使用demo参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/text_classification/text_cls_predefine_net.py

**Comment by Masterkmp** [comment] 2020-09-21 02:04
> 
> 
> 你好！BiLSTM属于在paddlehub预置网络模块中。使用demo参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/demo/text_classification/text_cls_predefine_net.py
谢谢回答，已解决

**Comment by haoyuying** [comment] 2021-04-14 11:57
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:57 UTC
