### ISSUE TITLE
paddlehub 一键部署  TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by HaiLcoder** [PaddlePaddle/PaddleFormers#596] opened 2020-05-14 03:14 UTC
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：PaddleHub1.6.2，PaddlePaddle1.7.2
2）系统环境：系统类型win10，python版本3.6
- 复现信息：如为报错，请给出复现环境、复现步骤
不同的模型提交之后都会报同样的错误
C:\Users\Administrator>hub serving start -m lac
Warning: Windows cannot use multiprocess working mode, PaddleHub Serving will switch to single process mode
lac == 2.1.1
2020-05-14 10:58:34,038-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
2020-05-14 10:59:31,856-INFO: 127.0.0.1 - - [14/May/2020 10:59:31] "[37mGET / HTTP/1.1[0m" 200 -
Exception on /get/modules [POST]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\wrappers\base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\wrappers\base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

**Comment by ShenYuhan** [comment] 2020-05-14 03:35
请问您是启动之后就报错，还是启动后请求服务的时候报错呢？
如果是后者，麻烦您贴下请求的代码

**Comment by HaiLcoder** [comment] 2020-05-14 04:01
是请求服务后报错，报错就是 上面我复制的那个

**Comment by HaiLcoder** [comment] 2020-05-14 04:12
这是 pycharm的报错
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/test/test.py", line 14, in <module>
    print(json.dumps(r.json(), indent=4, ensure_ascii=False))
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


这是命令提示符的报错
2020-05-14 12:06:28,649-INFO:  * Running on http://0.0.0.0:8866/ (Press CTRL+C to quit)
Exception on /predict/text/lac [POST]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "c:\programdata\anaconda3\lib\site-packages\flask\app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\wrappers\base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\wrappers\base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "c:\programdata\anaconda3\lib\site-packages\werkzeug\test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
2020-05-14 12:09:13,876-INFO: 127.0.0.1 - - [14/May/2020 12:09:13] "[35m[1mPOST /predict/text/lac HTTP/1.1[0m" 500 -

**Comment by ShenYuhan** [comment] 2020-05-14 11:06
可以贴一下您请求的脚本吗，我这边好复现一下

**Comment by HaiLcoder** [comment] 2020-05-14 12:38
请求的脚本是你们示例给出的那个脚本，我在服务器部署是合适的，但在自己的电脑部署的时候会报错，打开http://localhost:8866/网址里面，点分类没有选项，我把paddle和paddlehub卸载了重新试了一下 ，还是不行。

**Comment by ShenYuhan** [comment] 2020-05-15 01:49
我看您部署用的是lac==2.1.1 那么您使用的demo是否是这个呢？https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.6/demo/serving/module_serving/lexical_analysis_lac/lac_2.1.0_serving_demo.py

另外您可以在请求脚本的第十七行，打印r.text，看下是什么返回信息

**Comment by HaiLcoder** [comment] 2020-05-15 06:29
<Response [500]>

**Comment by HaiLcoder** [comment] 2020-05-15 06:30
Traceback (most recent call last):
<Response [500]>
  File "C:/Users/Administrator/Desktop/test/test.py", line 19, in <module>
    print(json.dumps(r.json(), indent=4, ensure_ascii=False))
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\ProgramData\Anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
这是paycharm的报错

**Comment by ShenYuhan** [comment] 2020-05-15 08:26
您可以帮我明确几个信息吗
1 使用的模型和版本
2 使用的demo具体是哪个
我好复现下，目前看不出问题出在哪里

**Comment by haoyuying** [comment] 2021-04-14 12:53
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:53 UTC
