### ISSUE TITLE
当开启use_data_parallel=True时，必须指定一个gpu，否则报错

### ISSUE THREAD

**Issue by dickobe** [PaddlePaddle/PaddleFormers#879] opened 2020-09-04 12:32 UTC
![image](https://user-images.githubusercontent.com/9254170/92239419-90124e00-eeed-11ea-9188-087fa29b5c9e.png)
为什么当开启use_data_parallel=True时，必须指定一个gpu运行，如果不指定或指定多个的是否都会报错

**Comment by Steffy-zxf** [comment] 2020-09-06 07:28
你好！报错信息是什么样的呢？

**Comment by haoyuying** [comment] 2021-04-14 12:01
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:01 UTC
