### ISSUE TITLE
Fail to open accelerate mode paddle < 1.6.2.

### ISSUE THREAD

**Issue by linyu0219** [PaddlePaddle/PaddleFormers#561] opened 2020-04-29 10:26 UTC
在aistudio上,用算力卡
用puddlehub的文本分类task,cls_task_.predict(data)但显示却不支持预测加速模式
aistudio上paddlepaddle是1.6.2啊

**Comment by kinghuin** [comment] 2020-04-29 11:54
Hi，@linyu0219，请升级paddle至>=1.6.3

**Comment by haoyuying** [comment] 2021-04-14 12:43
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:43 UTC
