### ISSUE TITLE
Is it necessary to specify the backend? Since 'Agg' will stop plt.show() in jupyter notebook img display

### ISSUE THREAD

**Issue by randomseed42** [PaddlePaddle/PaddleFormers#924] opened 2020-09-25 02:13 UTC
https://github.com/PaddlePaddle/PaddleHub/blob/2758efec5be1dc983557aa8ed8dd4fbea53e5afc/paddlehub/contrib/ppdet/utils/coco_eval.py#L26

![图片](https://user-images.githubusercontent.com/50793718/94218734-a7a28c80-ff17-11ea-8bcb-2b88075e3081.png)

**Comment by haoyuying** [comment] 2020-09-27 06:12
Thank you for your contribution to PaddleHub!
You may add %matplotlib inline under matplotlib.use('Agg') like this:

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
%matplotlib inline

**Comment by haoyuying** [comment] 2021-04-14 11:51
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:51 UTC
