### ISSUE TITLE
视频检测

### ISSUE THREAD

**Issue by sherklock** [PaddlePaddle/PaddleFormers#628] opened 2020-05-26 10:30 UTC
有没有什么办法可以检测视频中人物是否佩带口罩？

**Comment by Steffy-zxf** [comment] 2020-05-26 11:10
你好！参考issue回复   #621

**Comment by haoyuying** [comment] 2021-04-14 12:49
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:49 UTC
