### ISSUE TITLE
请问能不能给一个 自定义迁移任务 的例子。

### ISSUE THREAD

**Issue by wu8320175** [PaddlePaddle/PaddleFormers#786] opened 2020-07-29 08:31 UTC
不知道如何在hub里面进行自定义组网。

**Comment by Steffy-zxf** [comment] 2020-07-29 11:15
你好，关于自定义迁移任务，可以参考文档：
https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/how_to_define_task.md

https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/docs/tutorial/define_task_example.md

**Comment by haoyuying** [comment] 2021-04-14 12:27
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:27 UTC
