### ISSUE TITLE
AttributeError: module 'paddlehub' has no attribute 'BertTokenizer'

### ISSUE THREAD

**Issue by myboyliu** [PaddlePaddle/PaddleFormers#963] opened 2020-10-16 03:11 UTC
版本、环境信息
1）PaddleHub和PaddlePaddle版本：paddlehub   1.7.1，PaddlePaddle1.8.3
2）系统环境：Linux ubuntu18.04
- 复现信息：
sequence_label.py运行时候出现下面错误：
AttributeError: module 'paddlehub' has no attribute 'BertTokenizer'

**Comment by Steffy-zxf** [comment] 2020-10-18 09:26
你好！请升级paddlehub版本至1.8.0以上。

**Comment by haoyuying** [comment] 2021-04-14 11:44
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:44 UTC
