### ISSUE TITLE
请问paddlehub中squad数据集的机器阅读理解使用的是哪种模型？

### ISSUE THREAD

**Issue by SDUwn** [PaddlePaddle/PaddleFormers#725] opened 2020-06-30 04:06 UTC
请问paddlehub的机器阅读理解模型使用的是诸如BIDAF，r-net等的哪种经典模型还是自创的新模型呢？

**Comment by Steffy-zxf** [comment] 2020-06-30 06:51
你好！PaddleHub [机器阅读理解任务demo](https://github.com/PaddlePaddle/PaddleHub/tree/release/v1.7/demo/reading_comprehension)使用模型是BERT。

**Comment by haoyuying** [comment] 2021-04-14 12:31
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:31 UTC
