### ISSUE TITLE
PaddleHub pyinstaller时报错

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleFormers#940] opened 2020-10-09 07:41 UTC
ver:1.7
建议把pip list写入readme，我们好参考一下版本号

35162 INFO: Excluding import 'gtk'
35167 INFO: Loading module hook "hook-jedi.py"...
35234 INFO: Loading module hook "hook-jinja2.py"...
35246 INFO: Loading module hook "hook-jsonschema.py"...
35248 INFO: Loading module hook "hook-lib2to3.py"...
35250 INFO: Loading module hook "hook-lxml.etree.py"...
35250 INFO: Loading module hook "hook-matplotlib.backends.py"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 901, in <module>
    fail_on_error=True)
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 796, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "d:\anaconda3\envs\chineseocr\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 770, in _open_file_or_url
    fname = os.path.expanduser(fname)
  File "d:\anaconda3\envs\chineseocr\lib\ntpath.py", line 313, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not WindowsPath
35434 INFO: Loading module hook "hook-matplotlib.py"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 901, in <module>
    fail_on_error=True)
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 796, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "d:\anaconda3\envs\chineseocr\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "d:\anaconda3\envs\chineseocr\lib\site-packages\matplotlib\__init__.py", line 770, in _open_file_or_url
    fname = os.path.expanduser(fname)
  File "d:\anaconda3\envs\chineseocr\lib\ntpath.py", line 313, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not WindowsPath
35666 INFO: Loading module hook "hook-nbconvert.py"...
35674 INFO: Loading module hook "hook-nbformat.py"...
35676 INFO: Loading module hook "hook-nltk.py"...
Unable to find "C:\Users\1\nltk_data" when adding binary and data files.

**Comment by Steffy-zxf** [comment] 2020-10-10 01:35
你好！

关于PaddleHub的依赖可以参考：https://github.com/PaddlePaddle/PaddleHub/blob/release/v1.8/requirements.txt

以上报错信息，没有看到和PaddleHub相关信息。请问是要打包什么相关代码？

**Comment by haoyuying** [comment] 2021-04-14 11:47
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 11:47 UTC
