### ISSUE TITLE
使用Bert进行迁移学习报错

### ISSUE THREAD

**Issue by wu8320175** [PaddlePaddle/PaddleFormers#788] opened 2020-07-29 09:05 UTC
项目地址在这：https://aistudio.baidu.com/aistudio/projectdetail/661198
为啥会提示少一个梯度裁剪参数？
AttributeError: 'Parameter' object has no attribute 'gradient_clip_attr'

![image](https://user-images.githubusercontent.com/24267883/88780378-7fb7d680-d1bd-11ea-91d1-21fbe3e6fa02.png)

**Comment by Steffy-zxf** [comment] 2020-07-29 11:12
你好！请升级Paddle版本为1.8.0以上，paddlehub升级1.7.0版本以上。

**Comment by haoyuying** [comment] 2021-04-14 12:27
Since you haven't replied for more than 3 months, we have closed this issue/pr.
If the problem is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
由于您超过三个月未回复，我们将关闭这个issue/pr。
若问题未解决或有后续问题，请随时重新打开，我们会继续跟进。

**Closed as completed by haoyuying** 2021-04-14 12:27 UTC
Labels: nlp
